export const PAGE_REQUEST_START = 'category@page_request_start'
export const PAGE_REQUEST_END = 'category@page_request_end'
export const SET_PAGES = 'category@set_pages'
export const SET_CATEGORIES = 'category@set_categories'
export const CLEAR_LIST = 'category@clear_list'
